### ISSUE TITLE
undefined local variable or method `props' for UserSchema:Class

### ISSUE THREAD

**Issue by samlehman** [oreshinya/normalizr_ruby#1]
I'm trying to setup a `prop` on my UserSchema, but my schema doesn't seem to have access to `props`.

```
NameError (undefined local variable or method `props' for UserSchema:Class
Did you mean?  proc):

app/schemas/user_schema.rb:10:in `<class:UserSchema>'
app/schemas/user_schema.rb:3:in `<top (required)>'
app/schemas/authentication_token_schema.rb:6:in `<class:AuthenticationTokenSchema>'
app/schemas/authentication_token_schema.rb:1:in `<top (required)>'
app/controllers/authentication_tokens_controller.rb:9:in `create'
```

```
# app/schemas/user_schema.rb
class UserSchema < NormalizrRuby::Schema
  extend TypeCheck

  attribute :id, type: integer
  attribute :name, type: string
  attribute :email, type: string

  association :role, schema: RoleSchema, if: props[:with_role]
end
```

```
# app/schemas/authentication_token_schema.rb
class AuthenticationTokenSchema < NormalizrRuby::Schema
  extend TypeCheck
  attribute :id, type: string
  attribute :active, type: boolean

  association :user, schema: UserSchema
end
```

```
# app/schemas/role_schama.rb
class RoleSchema < NormalizrRuby::Schema
  attribute :id, type: integer
  attribute :name, type: string
  attribute :description, type: string
end
```

Any idea?

**Comment by samlehman** [comment]
Ruby 2.4.1
Rails 5.0.2

**Comment by samlehman** [comment]
After consulting with a  co-worker, was able to come up with this solution:

```
class UserSchema < ApplicationSchema
  attribute :id, type: integer
  attribute :name, type: string
  attribute :email, type: string

  association :role, schema: RoleSchema, if: :role?

  def role?
    -> { props[:with_role] }
  end
end
```
